# Generated by Django 4.1.5 on 2023-02-21 21:05

import logging
import os

from django.conf import settings
from django.core.management import call_command
from django.db import migrations

log = logging.getLogger(__name__)


def load_biosql(apps, schema_editor):
    if settings.ENVIRONMENT != "production":
        # for CI testing purposes
        # we don't need to download the data everytime
        log.info("pouring biosql schema with local dump data")
        sql_dir = os.path.join(os.path.dirname(__file__), "..", "sql")
        conn = schema_editor.connection
        with conn.cursor() as cursor:
            with open(os.path.join(sql_dir, "biosql-testing-dump.sql")) as file:
                cursor.execute(file.read())

    else:
        log.info("pouring biosql schema with real data")
        call_command("loadbiosql")
        log.info("done pouring biosql schema with real data")


def drop_biosql(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute("DROP SCHEMA biosql CASCADE")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(load_biosql, drop_biosql),
    ]
