# Generated by Django 4.1.8 on 2023-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biosql", "0001_biosql_manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dbxref",
            fields=[
                ("dbxref_id", models.AutoField(primary_key=True, serialize=False)),
                ("dbname", models.CharField(max_length=40)),
                ("accession", models.CharField(max_length=128)),
                ("version", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "DBXRefs",
                "db_table": 'biosql"."dbxref',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                ("taxon_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ncbi_taxon_id", models.IntegerField(null=True, unique=True)),
                ("parent_taxon_id", models.IntegerField(db_index=True, null=True)),
                ("node_rank", models.CharField(max_length=32, null=True)),
                ("genetic_code", models.SmallIntegerField(null=True)),
                ("mito_genetic_code", models.SmallIntegerField(null=True)),
                ("left_value", models.IntegerField(null=True, unique=True)),
                ("right_value", models.IntegerField(null=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Taxons",
                "db_table": 'biosql"."taxon',
                "managed": False,
            },
        ),
    ]
