# Generated by Django 4.1.13 on 2024-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('name_class', models.CharField(db_index=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Taxon names',
                'db_table': 'biosql"."taxon_name',
                'managed': False,
            },
        ),
    ]
