# Generated by Django 4.1.13 on 2024-08-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '0003_taxonname'),
    ]

    incorrect_end_loc = 3841420
    correct_end_loc = 3841348

    ncbi_wrong_prot_alr_id = 'NP_217940.1'
    uniprot_correct_prot_alr_id = 'P9WQA9'

    original_alr_prot_sequence = "".join("""
        MKRFWENVGKPNDTTDGRGTTSLAMTPISQTPGLLAEAMVDLGAIEHNVRVLREHAGHAQLMAVVKADGY
        GHGATRVAQTALGAGAAELGVATVDEALALRADGITAPVLAWLHPPGIDFGPALLADVQVAVSSLRQLDE
        LLHAVRRTGRTATVTVKVDTGLNRNGVGPAQFPAMLTALRQAMAEDAVRLRGLMSHMVYADKPDDSINDV
        QAQRFTAFLAQAREQGVRFEVAHLSNSSATMARPDLTFDLVRPGIAVYGLSPVPALGDMGLVPAMTVKCA
        VALVKSIRAGEGVSYGHTWIAPRDTNLALLPIGYADGVFRSLGGRLEVLINGRRCPGVGRICMDQFMVDL
        GPGPLDVAEGDEAILFGPGIRGEPTAQDWADLVGTIHYEVVTSPRGRITRTYREAENR
    """.split())

    original_alr_full_prot_sequence = "".join("""
        MetLysArgPheTrpGluAsnValGlyLysProAsnAspThrThrAspGlyArgGlyThrThrSer
        LeuAlaMetThrProIleSerGlnThrProGlyLeuLeuAlaGluAlaMetValAspLeuGlyAlaIle
        GluHisAsnValArgValLeuArgGluHisAlaGlyHisAlaGlnLeuMetAlaValValLysAlaAsp
        GlyTyrGlyHisGlyAlaThrArgValAlaGlnThrAlaLeuGlyAlaGlyAlaAlaGluLeuGlyVal
        AlaThrValAspGluAlaLeuAlaLeuArgAlaAspGlyIleThrAlaProValLeuAlaTrpLeuHis
        ProProGlyIleAspPheGlyProAlaLeuLeuAlaAspValGlnValAlaValSerSerLeuArgGln
        LeuAspGluLeuLeuHisAlaValArgArgThrGlyArgThrAlaThrValThrValLysValAspThr
        GlyLeuAsnArgAsnGlyValGlyProAlaGlnPheProAlaMetLeuThrAlaLeuArgGlnAlaMet
        AlaGluAspAlaValArgLeuArgGlyLeuMetSerHisMetValTyrAlaAspLysProAspAspSer
        IleAsnAspValGlnAlaGlnArgPheThrAlaPheLeuAlaGlnAlaArgGluGlnGlyValArgPhe
        GluValAlaHisLeuSerAsnSerSerAlaThrMetAlaArgProAspLeuThrPheAspLeuValArg
        ProGlyIleAlaValTyrGlyLeuSerProValProAlaLeuGlyAspMetGlyLeuValProAlaMet
        ThrValLysCysAlaValAlaLeuValLysSerIleArgAlaGlyGluGlyValSerTyrGlyHisThr
        TrpIleAlaProArgAspThrAsnLeuAlaLeuLeuProIleGlyTyrAlaAspGlyValPheArgSer
        LeuGlyGlyArgLeuGluValLeuIleAsnGlyArgArgCysProGlyValGlyArgIleCysMetAsp
        GlnPheMetValAspLeuGlyProGlyProLeuAspValAlaGluGlyAspGluAlaIleLeuPheGly
        ProGlyIleArgGlyGluProThrAlaGlnAspTrpAlaAspLeuValGlyThrIleHisTyrGluVal
        ValThrSerProArgGlyArgIleThrArgThrTyrArgGluAlaGluAsnArg
    """.split())

    operations = [
            # We need to fix the alr gene, which is missannotated in the reference
            # The protein is 24aa shorter than what the current annotation reflects
            # We need to change the right boundary of the gene (it is on the rev strand)
            # And modify the protein sequence as well
            migrations.RunSQL(
                sql=[("""
                UPDATE biosql.location
                    SET
                        end_pos = %s
                    WHERE
                        end_pos = %s;
                """, [correct_end_loc, incorrect_end_loc]
                )],
                reverse_sql=[("""
                UPDATE biosql.location
                    SET
                        end_pos = %s
                    WHERE
                        end_pos = %s;
                """, [incorrect_end_loc, correct_end_loc]
                )]
            ),
            migrations.RunSQL(
                sql = [("""
                UPDATE biosql.seqfeature_qualifier_value
                    SET
                        value = %s
                    WHERE
                        value = %s;
                """, [uniprot_correct_prot_alr_id, ncbi_wrong_prot_alr_id]
                )],
                reverse_sql=[("""            
                UPDATE biosql.seqfeature_qualifier_value
                    SET
                        value = %s
                    WHERE
                        value = %s;
                """, [ncbi_wrong_prot_alr_id, uniprot_correct_prot_alr_id]
                )]
            ),
            migrations.RunSQL(
                sql = [(
                    'UPDATE biosql.seqfeature_qualifier_value SET value = %s WHERE value = %s', 
                        [
                            original_alr_prot_sequence[24:],
                            original_alr_prot_sequence,
                        ]
                    )],
                reverse_sql = [(
                    'UPDATE biosql.seqfeature_qualifier_value SET value = %s WHERE value = %s', 
                        [
                            original_alr_prot_sequence,
                            original_alr_prot_sequence[24:],
                        ]
                    )]
            ),
            migrations.RunSQL(
                sql = [(
                    'UPDATE biosql.seqfeature_qualifier_value SET value = %s WHERE value = %s', 
                        [
                            original_alr_full_prot_sequence[72:],
                            original_alr_full_prot_sequence,
                        ]
                    )],
                reverse_sql = [(
                    'UPDATE biosql.seqfeature_qualifier_value SET value = %s WHERE value = %s', 
                        [
                            original_alr_full_prot_sequence,
                            original_alr_full_prot_sequence[72:],
                        ]
                    )]
            ),
    ]
