# Generated by Django 4.1.5 on 2023-04-14 13:27

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import identity.models.user
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("genphen", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", identity.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="identity.user",
                    ),
                ),
                ("institution_name", models.CharField(max_length=1024)),
                (
                    "institution_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                    ),
                ),
                ("institution_head_name", models.CharField(max_length=1024)),
                ("institution_head_email", models.EmailField(max_length=254)),
                (
                    "verification_state",
                    django_fsm.FSMField(
                        choices=[
                            ("NOT_VERIFIED", "Not verified"),
                            ("PENDING_VERIFICATION", "Pending verification"),
                            ("VERIFIED", "Verified"),
                        ],
                        default="NOT_VERIFIED",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "institution_country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="genphen.country",
                    ),
                ),
            ],
        ),
    ]
