# Generated by Django 4.1.10 on 2023-08-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
