# Generated by Django 4.1.5 on 2023-04-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0003_alter_samplealias_match_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="bioanalysis_status",
            field=models.CharField(
                choices=[
                    ("Unprocessed", "Unprocessed"),
                    ("Processing", "Processing"),
                    ("Extracted", "Extracted"),
                    ("Failed to extract", "Failed To Extract"),
                    ("Uploaded to S3", "Uploaded To S3"),
                    ("Failed to upload", "Failed To Upload"),
                    ("Inserted", "Inserted"),
                    ("Annotated", "Annotated"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
