# Generated by Django 4.1.5 on 2023-07-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_sample_bioanalysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingdata',
            name='s3_storage_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('DEEP_ARCHIVE', 'Deep Archive')], default='STANDARD', max_length=50, null=True),
        ),
    ]
