# Generated by Django 4.1.13 on 2024-02-20 16:23

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genphen', '0008_remove_variant_variant_chr_pos_ref_alt_key_and_more'),
        ('submission', '0005_sequencingdata_data_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='additional_geographical_information',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bioanalysis_status',
            field=models.CharField(blank=True, choices=[('None', 'Unset'), ('Unprocessed', 'Unprocessed'), ('Processing', 'Processing'), ('Extracted', 'Extracted'), ('Failed to extract', 'Failed To Extract'), ('Uploaded to S3', 'Uploaded To S3'), ('Failed to upload', 'Failed To Upload'), ('Inserted', 'Inserted'), ('Annotated', 'Annotated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='genphen.country'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='isolation_source',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='latitude',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='longitude',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='origin',
            field=models.CharField(blank=True, choices=[('None', 'Unset'), ('NCBI', 'Ncbi'), ('TbKb', 'Tbkb')], default='TbKb', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampling_date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
    ]
