# Generated by Django 4.1.13 on 2024-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_alter_sample_additional_geographical_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotyperesistance',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
