# Generated by Django 4.1.13 on 2024-07-22 13:10

from django.db import migrations, models
import submission.util.storage


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_genotyperesistance_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingdata',
            name='assay',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='dna_selection',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='dna_source',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='filename',
            field=models.FileField(blank=True, null=True, storage=submission.util.storage.FastqPermanentStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='library_layout',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='library_preparation_strategy',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='sequencing_machine',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='sequencing_platform',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
    ]
