# Generated by Django 4.1.13 on 2024-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_alter_sequencingdata_assay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingdata',
            name='library_name',
            field=models.CharField(blank=True, max_length=8192),
        ),
    ]
