# Generated by Django 4.1.13 on 2024-09-11 12:47

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_alter_sequencingdata_library_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='matching_state',
            field=models.CharField(choices=[('NEVER_MATCHED', 'Never Matched'), ('MATCHED', 'Matched'), ('CHANGED', 'Changed'), ('', 'Unset')], default='NEVER_MATCHED', max_length=32),
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('', 'Unset')], default='DRAFT', max_length=50),
        ),
    ]
