# Generated by Django 4.0 on 2022-10-17 08:51

import os

import pycountry
from django.db import migrations

GENPHEN_SQL = [
    "0001_1_schema.sql",
    "0001_2_tables.sql",
    "0001_3_finish.sql",
]


def create_genphen(apps, schema_editor):
    sql_dir = os.path.join(os.path.dirname(__file__), "..", "sql")
    conn = schema_editor.connection

    with conn.cursor() as cursor:
        for filename in GENPHEN_SQL:
            print("applying", filename)
            with open(os.path.join(sql_dir, filename)) as file:
                cursor.execute(file.read())


def drop_genphen(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute("DROP SCHEMA genphensql CASCADE")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biosql", "0001_biosql_manual"),
    ]

    operations = [
        migrations.RunPython(create_genphen, drop_genphen),
    ]
