# Generated by Django 4.1.5 on 2023-04-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("genphen", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=1024)),
                ("grade_version", models.IntegerField()),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_grades",
                        to="genphen.drug",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="genphen.variant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="variantgrade",
            constraint=models.UniqueConstraint(
                models.F("variant"),
                models.F("drug"),
                models.F("grade_version"),
                name="variantgrade_variant_drug_grade_version_key",
            ),
        ),
    ]
