# Generated by Django 4.1.5 on 2023-04-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("biosql", "0002_initial"),
        ("genphen", "0004_alter_genedrugresistanceassociation_drug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genedrugresistanceassociation",
            name="gene_db_crossref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="drug_resistance_associations",
                to="biosql.dbxref",
            ),
        ),
    ]
