# Generated by Django 4.1.5 on 2023-04-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("genphen", "0005_alter_genedrugresistanceassociation_gene_db_crossref"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicrodilutionPlateConcentration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(max_length=8192)),
                ("concentration", models.FloatField()),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genphen.drug",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="microdilutionplateconcentration",
            constraint=models.UniqueConstraint(
                models.F("plate"),
                models.F("drug"),
                models.F("concentration"),
                name="microdil_plate_drug_con_key",
            ),
        ),
    ]
