# Generated by Django 4.1.13 on 2024-06-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genphen', '0008_remove_variant_variant_chr_pos_ref_alt_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineage_numbering', models.CharField(max_length=20)),
                ('lineage_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='VariantLineageAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('alternative_nucleotide', models.CharField(max_length=1, null=True)),
                ('count_presence', models.BooleanField(default=True)),
                ('lineage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker', to='genphen.lineage')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineage_marker', to='genphen.variant')),
            ],
        ),
    ]
