# Generated by Django 4.1.13 on 2024-07-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genphen', '0009_lineage_variantlineageassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgrade',
            name='alternative_nucleotide',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variantgrade',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variantgrade',
            name='reference_nucleotide',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variantgrade',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='genphen.variant'),
        ),
    ]
