# Generated by Django 4.1.13 on 2024-07-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '0003_taxonname'),
        ('genphen', '0010_variantgrade_alternative_nucleotide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('gene_db_crossref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='promoter_locations', to='biosql.dbxref')),
            ],
        ),
    ]
