# Generated by Django 4.1.5 on 2023-04-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("biosql", "0002_initial"),
        ("overview", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genesearchhistory",
            name="gene_db_crossref_id",
        ),
        migrations.RemoveField(
            model_name="genesearchhistory",
            name="id",
        ),
        migrations.AddField(
            model_name="genesearchhistory",
            name="gene_db_crossref",
            field=models.OneToOneField(
                default=7,
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                related_name="search_history",
                serialize=False,
                to="biosql.dbxref",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="genesearchhistory",
            name="counter",
            field=models.IntegerField(default=0),
        ),
    ]
