-- fill genphen_drug and all related tables
INSERT INTO "genphen_drug"("drug_name", "drug_code")
SELECT
    x."Drug",
    x."PreferredCode"
FROM (
  VALUES
  ('H', 'Isoniazid', 'INH'),
  ('R', 'Rifampicin', 'RIF'),
  ('S', 'Streptomycin', 'STR'),
  ('E', 'Ethambutol', 'EMB'),
  ('Ofx', 'Ofloxacin', 'OFX'),
  ('Cm', 'Capreomycin', 'CAP'),
  ('Am', 'Amikacin', 'AMK'),
  ('Km', 'Kanamycin', 'KAN'),
  ('Z', 'Pyrazinamide', 'PZA'),
  ('Lfx', 'Levofloxacin', 'LFX'),
  ('Mfx', 'Moxifloxacin', 'MFX'),
  ('Cs', 'Cycloserine', 'CYC'),
  ('Eto', 'Ethionamide', 'ETO'),
  ('Dld', 'Delamanid', 'DLM'),
  ('Bdq', 'Bedaquiline', 'BDQ'),
  ('Lzd', 'Linezolid', 'LZD'),
  ('Cfz', 'Clofazimine', 'CFZ'),
  ('PMD', 'Pretomanid', 'PMD'),
  -- no preferred code for drugs below - use standard
  ('Pas', 'Para-Aminosalicylic Acid', 'PAS'),
  ('Pto', 'Prothionamide', 'PTO'),
  ('Amx/Clv','Amoxicillin-Clavulanate', 'AMX/CLV'),
  ('Mb', 'Rifabutin', 'MB'),
  ('Ipm/Cln', 'Imipenem-Cilastatin', 'IPM/CLN'),
  ('Clr', 'Clarithromycin', 'CLR'),
  ('Ft', 'Fluoroquinolones', 'FT'),
  ('AG/CP', 'Aminoglycosides', 'AG/CP'),
  ('Gfx', 'Gatifloxacin', 'GFX'),
  ('Cip', 'Ciprofloxacin', 'CIP'),
  ('Sit', 'Sitafloxacin', 'SIT'),
  ('Azt', 'Azithromycin', 'AZT')
  ) x("Synonym", "Drug", "PreferredCode")
;

INSERT INTO "genphen_drugsynonym"("drug_id", "drug_name_synonym")
SELECT
    "genphen_drug"."drug_id",
    x."Synonym"
FROM (
  VALUES
  ('H', 'Isoniazid'),
  ('R', 'Rifampicin'),
  ('S', 'Streptomycin'),
  ('E', 'Ethambutol'),
  ('Ofx', 'Ofloxacin'),
  ('Cm', 'Capreomycin'),
  ('Am', 'Amikacin'),
  ('Km', 'Kanamycin'),
  ('Z', 'Pyrazinamide'),
  ('Lfx', 'Levofloxacin'),
  ('Mfx', 'Moxifloxacin'),
  ('Pas', 'Para-Aminosalicylic Acid'),
  ('Pto', 'Prothionamide'),
  ('Cs', 'Cycloserine'),
  ('Dcs', 'Cycloserine'),
  ('Amx/Clv','Amoxicillin-Clavulanate'),
  ('Mb', 'Rifabutin'),
  ('Eto', 'Ethionamide'),
  ('Dld', 'Delamanid'),
  ('Bdq', 'Bedaquiline'),
  ('Ipm/Cln', 'Imipenem-Cilastatin'),
  ('Lzd', 'Linezolid'),
  ('Cfz', 'Clofazimine'),
  ('Clr', 'Clarithromycin'),
  ('Ft', 'Fluoroquinolones'),
  ('AG/CP', 'Aminoglycosides'),
  ('Gfx', 'Gatifloxacin'),
  ('Cip', 'Ciprofloxacin'),
  ('Sit', 'Sitafloxacin'),
  ('Azt', 'Azithromycin'),
  ('Pa', 'Pretomanid'),
  ('PA-824', 'Pretomanid'),
  ('Mycobutin', 'Rifabutin')
  ) x("Synonym", "Drug")
INNER JOIN "genphen_drug" on "genphen_drug"."drug_name"=x."Drug";

INSERT INTO "genphen_drugsynonym"("drug_id", "code", "drug_name_synonym")
SELECT
    "genphen_drug"."drug_id",
    'three_letter_code',
    x."Synonym"
FROM (
  VALUES
    ('INH', 'Isoniazid'),
    ('RIF', 'Rifampicin'),
    ('STR', 'Streptomycin'),
    ('STM', 'Streptomycin'),
    ('EMB', 'Ethambutol'),
    ('PZA', 'Pyrazinamide'),
    ('LFX', 'Levofloxacin'),
    ('LVX', 'Levofloxacin'),
    ('LEV', 'Levofloxacin'),
    ('LEVO', 'Levofloxacin'),
    ('MFX', 'Moxifloxacin'),
    ('MXF', 'Moxifloxacin'),
    ('MOXI', 'Moxifloxacin'),
    ('MOX', 'Moxifloxacin'),
    ('OFX', 'Ofloxacin'),
    ('OFL', 'Ofloxacin'),
    ('CAP', 'Capreomycin'),
    ('AMK', 'Amikacin'),
    ('AMI', 'Amikacin'),
    ('KAN', 'Kanamycin'),
    ('ETH', 'Ethionamide'),
    ('ETO', 'Ethionamide'),
    ('PAS', 'Para-Aminosalicylic Acid'),
    ('PTO', 'Prothionamide'),
    ('DLM', 'Delamanid'),
    ('BDQ', 'Bedaquiline'),
    ('LZD', 'Linezolid'),
    ('CFZ', 'Clofazimine'),
    ('CLR', 'Clarithromycin'),
    ('GFX', 'Gatifloxacin'),
    ('CIP', 'Ciprofloxacin'),
    ('SIT', 'Sitafloxacin'),
    ('STX', 'Sitafloxacin'),
    ('AZM', 'Azithromycine'),
    ('GEN', 'Gentamicin'),
    ('MPM', 'Meropenem'),
    ('IMI', 'Imipenem'),
    ('CYC', 'Cycloserine'),
    ('DCS', 'Cycloserine'),
    ('RFB', 'Rifabutin'),
    ('PMD', 'Pretomanid')
) x("Synonym", "Drug")
INNER JOIN "genphen_drug" on "genphen_drug"."drug_name"=x."Drug"
;


INSERT INTO "genphen_epidemcutoffvalue"("drug_id", "medium_name", "value")
SELECT "genphen_drug"."drug_id", y."Plate", x."Value"
FROM (
    VALUES
    ('Isoniazid', 0.1),
    ('Rifampicin', 0.5),
    ('Ethambutol', 4),
    ('Moxifloxacin', 1),
    ('Levofloxacin', 1),
    ('Kanamycin', 4),
    ('Amikacin', 1),
    ('Rifabutin', 0.12),
    ('Clofazimine', 0.25),
    ('Linezolid', 1),
    ('Delamanid', 0.12),
    ('Bedaquiline', 0.25),
    ('Ethionamide', 4)
 ) x ("Name", "Value")
  INNER JOIN "genphen_drug" ON "genphen_drug"."drug_name"=x."Name",
  (
    VALUES
    ('UKMYC5'),
    ('UKMYC6')
  ) y ("Plate")
;


INSERT INTO "genphen_microdilutionplateconcentration"("plate", "drug_id", "concentration")
SELECT
    "Plate",
    "genphen_drugsynonym"."drug_id",
    "Concentration"
FROM (
  VALUES
    ('UKMYC5', 'AMI', 8),
    ('UKMYC5', 'AMI', 4),
    ('UKMYC5', 'AMI', 2),
    ('UKMYC5', 'AMI', 1),
    ('UKMYC5', 'AMI', 0.5),
    ('UKMYC5', 'AMI', 0.25),
    ('UKMYC5', 'BDQ', 2),
    ('UKMYC5', 'BDQ', 1),
    ('UKMYC5', 'BDQ', 0.5),
    ('UKMYC5', 'BDQ', 0.25),
    ('UKMYC5', 'BDQ', 0.12),
    ('UKMYC5', 'BDQ', 0.06),
    ('UKMYC5', 'BDQ', 0.03),
    ('UKMYC5', 'BDQ', 0.015),
    ('UKMYC5', 'CFZ', 4),
    ('UKMYC5', 'CFZ', 2),
    ('UKMYC5', 'CFZ', 1),
    ('UKMYC5', 'CFZ', 0.5),
    ('UKMYC5', 'CFZ', 0.25),
    ('UKMYC5', 'CFZ', 0.12),
    ('UKMYC5', 'CFZ', 0.06),
    ('UKMYC5', 'DLM', 1),
    ('UKMYC5', 'DLM', 0.5),
    ('UKMYC5', 'DLM', 0.25),
    ('UKMYC5', 'DLM', 0.12),
    ('UKMYC5', 'DLM', 0.06),
    ('UKMYC5', 'DLM', 0.03),
    ('UKMYC5', 'DLM', 0.015),
    ('UKMYC5', 'EMB', 8),
    ('UKMYC5', 'EMB', 4),
    ('UKMYC5', 'EMB', 2),
    ('UKMYC5', 'EMB', 1),
    ('UKMYC5', 'EMB', 0.5),
    ('UKMYC5', 'EMB', 0.25),
    ('UKMYC5', 'EMB', 0.06),
    ('UKMYC5', 'EMB', 0.12),
    ('UKMYC5', 'ETH', 8),
    ('UKMYC5', 'ETH', 4),
    ('UKMYC5', 'ETH', 2),
    ('UKMYC5', 'ETH', 1),
    ('UKMYC5', 'ETH', 0.5),
    ('UKMYC5', 'ETH', 0.25),
    ('UKMYC5', 'INH', 1.6),
    ('UKMYC5', 'INH', 0.8),
    ('UKMYC5', 'INH', 0.4),
    ('UKMYC5', 'INH', 0.2),
    ('UKMYC5', 'INH', 0.1),
    ('UKMYC5', 'INH', 0.05),
    ('UKMYC5', 'INH', 0.025),
    ('UKMYC5', 'KAN', 16),
    ('UKMYC5', 'KAN', 8),
    ('UKMYC5', 'KAN', 4),
    ('UKMYC5', 'KAN', 2),
    ('UKMYC5', 'KAN', 1),
    ('UKMYC5', 'LEV', 8),
    ('UKMYC5', 'LEV', 4),
    ('UKMYC5', 'LEV', 2),
    ('UKMYC5', 'LEV', 1),
    ('UKMYC5', 'LEV', 0.5),
    ('UKMYC5', 'LEV', 0.25),
    ('UKMYC5', 'LEV', 0.12),
    ('UKMYC5', 'LZD', 2),
    ('UKMYC5', 'LZD', 1),
    ('UKMYC5', 'LZD', 0.5),
    ('UKMYC5', 'LZD', 0.25),
    ('UKMYC5', 'LZD', 0.12),
    ('UKMYC5', 'LZD', 0.06),
    ('UKMYC5', 'LZD', 0.03),
    ('UKMYC5', 'MXF', 4),
    ('UKMYC5', 'MXF', 2),
    ('UKMYC5', 'MXF', 1),
    ('UKMYC5', 'MXF', 0.5),
    ('UKMYC5', 'MXF', 0.25),
    ('UKMYC5', 'MXF', 0.12),
    ('UKMYC5', 'MXF', 0.06),
    ('UKMYC5', 'PAS', 4),
    ('UKMYC5', 'PAS', 2),
    ('UKMYC5', 'PAS', 1),
    ('UKMYC5', 'PAS', 0.5),
    ('UKMYC5', 'PAS', 0.25),
    ('UKMYC5', 'PAS', 0.12),
    ('UKMYC5', 'RFB', 2),
    ('UKMYC5', 'RFB', 1),
    ('UKMYC5', 'RFB', 0.5),
    ('UKMYC5', 'RFB', 0.25),
    ('UKMYC5', 'RFB', 0.12),
    ('UKMYC5', 'RFB', 0.06),
    ('UKMYC5', 'RIF', 4),
    ('UKMYC5', 'RIF', 2),
    ('UKMYC5', 'RIF', 1),
    ('UKMYC5', 'RIF', 0.5),
    ('UKMYC5', 'RIF', 0.25),
    ('UKMYC5', 'RIF', 0.12),
    ('UKMYC5', 'RIF', 0.06),
    ('UKMYC6', 'AMI', 16),
    ('UKMYC6', 'AMI', 8),
    ('UKMYC6', 'AMI', 4),
    ('UKMYC6', 'AMI', 2),
    ('UKMYC6', 'AMI', 1),
    ('UKMYC6', 'AMI', 0.5),
    ('UKMYC6', 'AMI', 0.25),
    ('UKMYC6', 'BDQ', 1),
    ('UKMYC6', 'BDQ', 0.5),
    ('UKMYC6', 'BDQ', 0.25),
    ('UKMYC6', 'BDQ', 0.12),
    ('UKMYC6', 'BDQ', 0.06),
    ('UKMYC6', 'BDQ', 0.03),
    ('UKMYC6', 'BDQ', 0.015),
    ('UKMYC6', 'BDQ', 0.008),
    ('UKMYC6', 'CFZ', 2),
    ('UKMYC6', 'CFZ', 1),
    ('UKMYC6', 'CFZ', 0.5),
    ('UKMYC6', 'CFZ', 0.25),
    ('UKMYC6', 'CFZ', 0.12),
    ('UKMYC6', 'CFZ', 0.06),
    ('UKMYC6', 'CFZ', 0.03),
    ('UKMYC6', 'DLM', 0.5),
    ('UKMYC6', 'DLM', 0.25),
    ('UKMYC6', 'DLM', 0.12),
    ('UKMYC6', 'DLM', 0.06),
    ('UKMYC6', 'DLM', 0.03),
    ('UKMYC6', 'DLM', 0.015),
    ('UKMYC6', 'DLM', 0.008),
    ('UKMYC6', 'EMB', 32),
    ('UKMYC6', 'EMB', 16),
    ('UKMYC6', 'EMB', 8),
    ('UKMYC6', 'EMB', 4),
    ('UKMYC6', 'EMB', 2),
    ('UKMYC6', 'EMB', 1),
    ('UKMYC6', 'EMB', 0.5),
    ('UKMYC6', 'EMB', 0.25),
    ('UKMYC6', 'ETH', 8),
    ('UKMYC6', 'ETH', 4),
    ('UKMYC6', 'ETH', 2),
    ('UKMYC6', 'ETH', 1),
    ('UKMYC6', 'ETH', 0.5),
    ('UKMYC6', 'ETH', 0.25),
    ('UKMYC6', 'INH', 12.8),
    ('UKMYC6', 'INH', 6.4),
    ('UKMYC6', 'INH', 3.2),
    ('UKMYC6', 'INH', 1.6),
    ('UKMYC6', 'INH', 0.8),
    ('UKMYC6', 'INH', 0.4),
    ('UKMYC6', 'INH', 0.2),
    ('UKMYC6', 'INH', 0.1),
    ('UKMYC6', 'INH', 0.05),
    ('UKMYC6', 'INH', 0.025),
    ('UKMYC6', 'KAN', 16),
    ('UKMYC6', 'KAN', 8),
    ('UKMYC6', 'KAN', 4),
    ('UKMYC6', 'KAN', 2),
    ('UKMYC6', 'KAN', 1),
    ('UKMYC6', 'LEV', 8),
    ('UKMYC6', 'LEV', 4),
    ('UKMYC6', 'LEV', 2),
    ('UKMYC6', 'LEV', 1),
    ('UKMYC6', 'LEV', 0.5),
    ('UKMYC6', 'LEV', 0.25),
    ('UKMYC6', 'LEV', 0.12),
    ('UKMYC6', 'LZD', 4),
    ('UKMYC6', 'LZD', 2),
    ('UKMYC6', 'LZD', 1),
    ('UKMYC6', 'LZD', 0.5),
    ('UKMYC6', 'LZD', 0.25),
    ('UKMYC6', 'LZD', 0.12),
    ('UKMYC6', 'LZD', 0.06),
    ('UKMYC6', 'MXF', 4),
    ('UKMYC6', 'MXF', 2),
    ('UKMYC6', 'MXF', 1),
    ('UKMYC6', 'MXF', 0.5),
    ('UKMYC6', 'MXF', 0.25),
    ('UKMYC6', 'MXF', 0.12),
    ('UKMYC6', 'MXF', 0.06),
    ('UKMYC6', 'RIF', 8),
    ('UKMYC6', 'RIF', 4),
    ('UKMYC6', 'RIF', 2),
    ('UKMYC6', 'RIF', 1),
    ('UKMYC6', 'RIF', 0.5),
    ('UKMYC6', 'RIF', 0.25),
    ('UKMYC6', 'RIF', 0.12),
    ('UKMYC6', 'RIF', 0.06),
    ('UKMYC6', 'RIF', 0.03),
    ('UKMYC6', 'RFB', 2),
    ('UKMYC6', 'RFB', 1),
    ('UKMYC6', 'RFB', 0.5),
    ('UKMYC6', 'RFB', 0.25),
    ('UKMYC6', 'RFB', 0.12),
    ('UKMYC6', 'RFB', 0.06),
    ('MYCOTB', 'AMI', 16),
    ('MYCOTB', 'AMI', 8),
    ('MYCOTB', 'AMI', 4),
    ('MYCOTB', 'AMI', 2),
    ('MYCOTB', 'AMI', 1),
    ('MYCOTB', 'AMI', 0.5),
    ('MYCOTB', 'AMI', 0.25),
    ('MYCOTB', 'AMI', 0.12),
    ('MYCOTB', 'CYC', 256),
    ('MYCOTB', 'CYC', 128),
    ('MYCOTB', 'CYC', 64),
    ('MYCOTB', 'CYC', 32),
    ('MYCOTB', 'CYC', 16),
    ('MYCOTB', 'CYC', 8),
    ('MYCOTB', 'CYC', 4),
    ('MYCOTB', 'CYC', 2),
    ('MYCOTB', 'EMB', 32),
    ('MYCOTB', 'EMB', 16),
    ('MYCOTB', 'EMB', 8),
    ('MYCOTB', 'EMB', 4),
    ('MYCOTB', 'EMB', 2),
    ('MYCOTB', 'EMB', 1),
    ('MYCOTB', 'EMB', 0.5),
    ('MYCOTB', 'ETH', 40),
    ('MYCOTB', 'ETH', 20),
    ('MYCOTB', 'ETH', 10),
    ('MYCOTB', 'ETH', 5),
    ('MYCOTB', 'ETH', 2.5),
    ('MYCOTB', 'ETH', 1.2),
    ('MYCOTB', 'ETH', 0.6),
    ('MYCOTB', 'ETH', 0.3),
    ('MYCOTB', 'INH', 4),
    ('MYCOTB', 'INH', 2),
    ('MYCOTB', 'INH', 1),
    ('MYCOTB', 'INH', 0.5),
    ('MYCOTB', 'INH', 0.25),
    ('MYCOTB', 'INH', 0.12),
    ('MYCOTB', 'INH', 0.06),
    ('MYCOTB', 'INH', 0.03),
    ('MYCOTB', 'KAN', 40),
    ('MYCOTB', 'KAN', 20),
    ('MYCOTB', 'KAN', 10),
    ('MYCOTB', 'KAN', 5),
    ('MYCOTB', 'KAN', 2.5),
    ('MYCOTB', 'KAN', 1.2),
    ('MYCOTB', 'KAN', 0.6),
    ('MYCOTB', 'MXF', 8),
    ('MYCOTB', 'MXF', 4),
    ('MYCOTB', 'MXF', 2),
    ('MYCOTB', 'MXF', 1),
    ('MYCOTB', 'MXF', 0.5),
    ('MYCOTB', 'MXF', 0.25),
    ('MYCOTB', 'MXF', 0.12),
    ('MYCOTB', 'MXF', 0.06),
    ('MYCOTB', 'OFL', 32),
    ('MYCOTB', 'OFL', 16),
    ('MYCOTB', 'OFL', 8),
    ('MYCOTB', 'OFL', 4),
    ('MYCOTB', 'OFL', 2),
    ('MYCOTB', 'OFL', 1),
    ('MYCOTB', 'OFL', 0.5),
    ('MYCOTB', 'OFL', 0.25),
    ('MYCOTB', 'PAS', 64),
    ('MYCOTB', 'PAS', 32),
    ('MYCOTB', 'PAS', 16),
    ('MYCOTB', 'PAS', 8),
    ('MYCOTB', 'PAS', 4),
    ('MYCOTB', 'PAS', 2),
    ('MYCOTB', 'PAS', 1),
    ('MYCOTB', 'PAS', 0.5),
    ('MYCOTB', 'RFB', 16),
    ('MYCOTB', 'RFB', 8),
    ('MYCOTB', 'RFB', 4),
    ('MYCOTB', 'RFB', 2),
    ('MYCOTB', 'RFB', 1),
    ('MYCOTB', 'RFB', 0.5),
    ('MYCOTB', 'RFB', 0.25),
    ('MYCOTB', 'RFB', 0.12),
    ('MYCOTB', 'RIF', 16),
    ('MYCOTB', 'RIF', 8),
    ('MYCOTB', 'RIF', 4),
    ('MYCOTB', 'RIF', 2),
    ('MYCOTB', 'RIF', 1),
    ('MYCOTB', 'RIF', 0.5),
    ('MYCOTB', 'RIF', 0.25),
    ('MYCOTB', 'RIF', 0.12),
    ('MYCOTB', 'STR', 32),
    ('MYCOTB', 'STR', 16),
    ('MYCOTB', 'STR', 8),
    ('MYCOTB', 'STR', 4),
    ('MYCOTB', 'STR', 2),
    ('MYCOTB', 'STR', 1),
    ('MYCOTB', 'STR', 0.5),
    ('MYCOTB', 'STR', 0.25)
) x("Plate", "Code", "Concentration")
INNER JOIN "genphen_drugsynonym" on "genphen_drugsynonym"."drug_name_synonym"=x."Code";

INSERT INTO "genphen_growthmedium"("medium_name")
VALUES
  ('MGIT'),
  ('BACTEC460'),
  ('LJ'),
  ('Agar'),
  ('Middlebrook7H9'),
  ('Middlebrook7H10'),
  ('Middlebrook7H11'),
  ('Waynes'),
  ('Marks Biphasic'),
  ('MODS')
;

INSERT INTO "genphen_pdsassessmentmethod"("method_name")
VALUES
  ('Resistance Ratio'),
  ('Proportions'),
  ('Direct'),
  ('Nitrate reductase assay'),
  ('WHO')
;
